In [23]:
import pandas as pd
AOS100_data = pd.read_csv("AOS100_dataset_v2.csv")
AOS100_data

    Alcohol_gram  temp  humidity  TIME
0              0  25.1        60   137
1             10  24.8        59   131
2             20  24.7        61   142
3             30  24.6        61   128
4             40  24.7        61   129
5             50  24.8        61   132
6             60  24.7        60   136
7             70  24.7        61   137
8             80  24.7        62   125
9             90  24.7        62   138
10           100  24.8        63   134
11           110  25.0        61   138
12           120  25.0        62   144
13             0  25.3        64   111
14            10  25.0        64   117
15            20  25.1        63   110
16            30  25.2        63   129
17            40  25.3        65   108
18            50  25.3        64   117
19            60  25.3        64   124
20            70  25.1        62   130
21            80  25.0        61   128
22            90  25.0        61   157
23           100  24.9        61   138
24           110  24.8        62   158
25           120  24.9        62   150
26             0  25.1        60   137
27            10  24.8        59   131
28            20  24.7        61   142
29            30  24.6        61   128
30            40  24.7        61   129
31            50  24.8        61   132
32            60  24.7        60   136
33            70  24.7        61   137
34            80  24.7        62   125
35            90  24.7        62   138
36           100  24.8        63   134
37           110  25.0        61   138
38           120  25.0        62   144
39             0  25.3        64   111
40            10  25.0        64   117
41            20  25.1        63   110
42            30  25.2        63   129
43            40  25.3        65   108
44            50  25.3        64   117
45            60  25.3        64   124
46            70  25.1        62   130
47            80  25.0        61   128
48            90  25.0        61   157
49           100  24.9        61   138
50           110  24.8        62   158
51           120  24.9        62   150

# input（X）　output（y）の２つにデータを分ける

In [25]:
# input set
X = AOS100_data.drop(columns=["TIME"])

X

    Alcohol_gram  temp  humidity
0              0  25.1        60
1             10  24.8        59
2             20  24.7        61
3             30  24.6        61
4             40  24.7        61
5             50  24.8        61
6             60  24.7        60
7             70  24.7        61
8             80  24.7        62
9             90  24.7        62
10           100  24.8        63
11           110  25.0        61
12           120  25.0        62
13             0  25.3        64
14            10  25.0        64
15            20  25.1        63
16            30  25.2        63
17            40  25.3        65
18            50  25.3        64
19            60  25.3        64
20            70  25.1        62
21            80  25.0        61
22            90  25.0        61
23           100  24.9        61
24           110  24.8        62
25           120  24.9        62
26             0  25.1        60
27            10  24.8        59
28            20  24.7        61
29            30  24.6        61
30            40  24.7        61
31            50  24.8        61
32            60  24.7        60
33            70  24.7        61
34            80  24.7        62
35            90  24.7        62
36           100  24.8        63
37           110  25.0        61
38           120  25.0        62
39             0  25.3        64
40            10  25.0        64
41            20  25.1        63
42            30  25.2        63
43            40  25.3        65
44            50  25.3        64
45            60  25.3        64
46            70  25.1        62
47            80  25.0        61
48            90  25.0        61
49           100  24.9        61
50           110  24.8        62
51           120  24.9        62

In [26]:
# output set
y = AOS100_data["TIME"]

y

0     137
1     131
2     142
3     128
4     129
5     132
6     136
7     137
8     125
9     138
10    134
11    138
12    144
13    111
14    117
15    110
16    129
17    108
18    117
19    124
20    130
21    128
22    157
23    138
24    158
25    150
26    137
27    131
28    142
29    128
30    129
31    132
32    136
33    137
34    125
35    138
36    134
37    138
38    144
39    111
40    117
41    110
42    129
43    108
44    117
45    124
46    130
47    128
48    157
49    138
50    158
51    150
Name: TIME, dtype: int64

In [27]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
# fitでデータをモデルに入れる
model.fit(X,y)

DecisionTreeClassifier()

In [29]:
# 実際に予測

predictions = model.predict([[40, 25, 60], [100, 26, 65]])
print(predictions)

[136 134]

# trainとtestにわけて予測率を出す

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  #　４つtupleがでる

model.fit(X_train, y_train)
predictions = model.predict(X_test)


score = accuracy_score(y_test, predictions)
score

0.8181818181818182